[package]
name = "simple"
version = "0.1.151"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llama-cpp-2 = { path = "../../llama-cpp-2", version = "0.1.69" }
hf-hub = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
encoding_rs = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
cuda = ["llama-cpp-2/cuda"]
metal = ["llama-cpp-2/metal"]
vulkan = ["llama-cpp-2/vulkan"]
cann = ["llama-cpp-2/cann"]
cann-310p = ["llama-cpp-2/cann-310p"]
cann-910 = ["llama-cpp-2/cann-910"]
cann-910b = ["llama-cpp-2/cann-910b"]
cann-910c = ["llama-cpp-2/cann-910c"]
mkl = ["llama-cpp-2/mkl"]

[lints]
workspace = true
